"""TrendEngine：异步趋势分析调度器。"""

import asyncio
from collections import deque
from datetime import datetime, timedelta
from typing import Deque, List, Optional, Set

from astrbot.api import logger
from ..events import EventManager
from ..models import Event, EventLevel, Trend
from ..stream import ObservationStream
from .collector_strategy import FallbackMetricTrendStrategy
from .strategy import BaseTrendStrategy


class TrendEngine:
    """
    趋势分析引擎。

    职责：
    1. 按策略配置（metric + window）拉取 Observation
    2. 调用策略计算 Trend
    3. 对空数据与策略异常进行事件上报
    """

    stream: ObservationStream
    event_manager: EventManager
    event_queue: "asyncio.Queue[Event]"
    strategies: List[BaseTrendStrategy]
    trends: Deque[Trend]

    def __init__(
        self,
        stream: ObservationStream,
        event_manager: EventManager,
        fallback_window: timedelta = timedelta(seconds=30),
        fallback_interval: timedelta = timedelta(seconds=30),
        max_trends: int = 500,
    ) -> None:
        self.stream = stream
        self.event_manager = event_manager
        self.event_queue = self.event_manager.queue()
        self.strategies = []
        self.trends = deque(maxlen=max(1, int(max_trends)))
        self.fallback_strategy = FallbackMetricTrendStrategy(
            metric=None,
            window=fallback_window,
            interval=fallback_interval,
            name="FallbackMetricTrendStrategy",
        )
        self._running = False
        logger.info(
            f"TrendEngine initialized: fallback_window={fallback_window.total_seconds()}s "
            f"fallback_interval={fallback_interval.total_seconds()}s max_trends={self.trends.maxlen}"
        )

    def register_strategy(self, strategy: BaseTrendStrategy) -> None:
        """注册趋势策略。"""
        self.strategies.append(strategy)
        logger.info(
            f"Trend strategy registered: name={strategy.name} metric={strategy.metric or '*'} "
            f"window={strategy.window.total_seconds()}s interval={strategy.interval.total_seconds()}s"
        )

    def unregister_strategy(self, metric: str) -> None:
        """按 metric 注销策略。"""
        self.strategies = [strategy for strategy in self.strategies if strategy.metric != metric]
        logger.info(f"Trend strategy unregistered by metric: {metric}")

    async def analyze(self) -> List[Trend]:
        """
        执行一次异步分析。

        Returns:
            本轮产出的 Trend 列表。
        """
        analyzed_trends: List[Trend] = []
        now = datetime.now()
        now_ts = now.timestamp()
        logger.debug(f"Trend analyze start: strategies={len(self.strategies)}")
        covered_metrics = await self._analyze_explicit_strategies(now=now, now_ts=now_ts, results=analyzed_trends)
        await self._analyze_fallback_strategy(
            now=now,
            now_ts=now_ts,
            covered_metrics=covered_metrics,
            results=analyzed_trends,
        )
        logger.debug(f"Trend analyze done: generated={len(analyzed_trends)}")
        return analyzed_trends

    async def _analyze_explicit_strategies(
        self,
        now: datetime,
        now_ts: float,
        results: List[Trend],
    ) -> Set[str]:
        """分析显式注册的专用趋势策略。"""
        covered_metrics: Set[str] = set()
        for strategy in self.strategies:
            if not strategy.should_run(now_ts):
                logger.debug(f"Trend strategy skipped by interval: name={strategy.name}")
                continue

            start_time = now - strategy.window
            observations = self.stream.get_window(start=start_time, end=now)
            filtered = [obs for obs in observations if strategy.covers(obs.metric)]
            covered_metrics.update(obs.metric for obs in filtered)
            logger.debug(
                f"Trend strategy input prepared: name={strategy.name} observations={len(filtered)}"
            )
            try:
                for trend in strategy.compute_trends(filtered):
                    self.submit_trend(trend)
                    results.append(trend)
                    logger.debug(
                        f"Trend generated by explicit strategy: metric={trend.metric} "
                        f"series_key={trend.series_key} samples={trend.samples}"
                    )
            except Exception as exc:
                await self._emit_event(
                    event_type="TrendStrategyErrorEvent",
                    level=EventLevel.WARNING,
                    message=f"trend strategy '{strategy.name}' 执行失败: {exc}",
                    context={
                        "metric": strategy.metric,
                        "strategy_name": strategy.name,
                        "window_seconds": strategy.window.total_seconds(),
                        "error": repr(exc),
                    },
                )
            finally:
                strategy._last_run = now_ts
        return covered_metrics

    async def _analyze_fallback_strategy(
        self,
        now: datetime,
        now_ts: float,
        covered_metrics: Set[str],
        results: List[Trend],
    ) -> None:
        """分析内置兜底趋势策略。"""
        if not self.fallback_strategy.should_run(now_ts):
            logger.debug("Fallback trend strategy skipped by interval")
            return

        start_time = now - self.fallback_strategy.window
        observations = self.stream.get_window(start=start_time, end=now)
        filtered = [obs for obs in observations if obs.metric not in covered_metrics]
        logger.debug(
            f"Fallback trend input prepared: observations={len(filtered)} covered_metrics={sorted(covered_metrics)}"
        )
        try:
            for trend in self.fallback_strategy.compute_trends(filtered):
                self.submit_trend(trend)
                results.append(trend)
                logger.debug(
                    f"Trend generated by fallback strategy: metric={trend.metric} "
                    f"series_key={trend.series_key} samples={trend.samples}"
                )
        except Exception as exc:
            await self._emit_event(
                event_type="TrendStrategyErrorEvent",
                level=EventLevel.WARNING,
                message=f"trend strategy '{self.fallback_strategy.name}' 执行失败: {exc}",
                context={
                    "metric": self.fallback_strategy.metric,
                    "strategy_name": self.fallback_strategy.name,
                    "window_seconds": self.fallback_strategy.window.total_seconds(),
                    "error": repr(exc),
                },
            )
        finally:
            self.fallback_strategy._last_run = now_ts

    def submit_trend(self, trend: Trend) -> None:
        """提交 Trend 到引擎内部结果列表（供上层消费）。"""
        self.trends.append(trend)
        logger.debug(f"Trend submitted to buffer: metric={trend.metric} total={len(self.trends)}")

    async def run(self, interval: timedelta) -> None:
        """持续运行 TrendEngine，每 interval 执行一次 analyze()。"""
        self._running = True
        logger.info(f"TrendEngine run loop started (interval={interval.total_seconds()}s)")
        try:
            while self._running:
                await self.analyze()
                await asyncio.sleep(interval.total_seconds())
        finally:
            self._running = False
            logger.info("TrendEngine run loop stopped")

    def stop(self) -> None:
        """停止 run() 循环。"""
        self._running = False
        logger.info("TrendEngine stop requested")

    async def _emit_event(
        self,
        event_type: str,
        level: EventLevel,
        message: str,
        context: Optional[dict] = None,
    ) -> None:
        """写入趋势分析事件到 event_queue。"""
        await self.event_manager.submit_event(
            Event(
                type=event_type,
                level=level,
                message=message,
                timestamp=datetime.now(),
                context=context or {},
            )
        )
        logger.debug(f"Trend event emitted: type={event_type} level={level.value}")
